# Generated by Django 5.1.3 on 2024-11-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
