# Generated by Django 5.1.3 on 2024-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced', '0002_alter_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='probability',
            field=models.FloatField(default=0),
        ),
    ]
